# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${self:custom.secrets.org}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dforbreakfast
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dforbreakfast

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${self:custom.secrets.role}
  httpApi:
    cors: true

custom:
  secrets: ${file(./personal.yml)}

functions:
  CreateProducts:
    handler: functions/products/CreateProducts/index.handler
    events:
      - httpApi:
          path: /products
          method: post
  GetAllProducts:
    handler: functions/products/GetAllProducts/index.handler
    events:
      - httpApi:
          path: /products
          method: get
  GetProduct:
    handler: functions/products/GetProduct/index.handler
    events:
      - httpApi:
          path: /products/{id}
          method: get
  DeleteProducts:
    handler: functions/products/DeleteProducts/index.handler
    events:
      - httpApi:
          path: /products/{id}
          method: delete
  UpdateProducts:
    handler: functions/products/UpdateProducts/index.handler
    events:
      - httpApi:
          path: /products/{id}
          method: put
resources:
  Resources:
    menuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: menuTable # Namnet på din tabell
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id # Partition key
            KeyType: HASH # Detta är din PK (Partition Key)
        BillingMode: PAY_PER_REQUEST # Betalning per användning
